services/netauth: document initial setup.
void-linux/void-infrastructure pull request #94
Opened 2020-12-19 05:15 UTC by ericonr

2020-12-21 08:03 UTC, the-maldridge requested changes

2020-12-21 08:03 UTC, the-maldridge commented on docs/src/services/netauth.md
> +to systems within Void's managed fleet. NetAuth is an open source
Style in this repo is 2 spaces after periods.

2020-12-21 08:03 UTC, the-maldridge commented on docs/src/services/netauth.md
> +$ openssl s_client -showcerts -connect netauth.voidlinux.org:1729 </dev/null | openssl x509 -outform pem
Please also show the cfssl/jq version, it was generally nicer in my opinion.

2020-12-21 15:18 UTC, ericonr commented
Done

2020-12-29 06:24 UTC, ericonr commented
Ping @the-maldridge

2020-12-29 06:26 UTC, merged